#!/usr/bin/env python3
"""Build compact top-k LOO table from mean_only_long.csv."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "figures" / "data" / "mean_only_long.csv"
OUT_MD = ROOT / "tables" / "loo_topk_mean_only.md"
OUT_TEX = ROOT / "latex" / "table_loo_topk.tex"
K = 10


def feat_short(s: str) -> str:
    s = str(s).replace("daily: mean", "daily").replace("night: mean", "night")
    s = s.replace("day: mean", "day")
    return s.replace("; ", "+")


def lik_short(s: str) -> str:
    return {"student_t": "Student-$t$", "skew_normal": "skew-normal"}.get(s, s)


def feat_tex(s: str) -> str:
    # Keep twocolumn-friendly abbreviations for the longest label only.
    if s == "daily+day+night":
        return "d+day+nig."
    return s


def main() -> None:
    df = pd.read_csv(CSV)
    assert len(df) == 84, f"expected 84 mean-only rows, got {len(df)}"
    df = df.sort_values("elpd_loo_per_feature_day", ascending=False).head(K).copy()
    df["rank"] = range(1, len(df) + 1)

    rows = []
    for _, r in df.iterrows():
        rows.append(
            {
                "rank": int(r["rank"]),
                "features": feat_short(r["features"]),
                "lik": lik_short(r["mean_lik"]),
                "N": int(r["n_points"]),
                "ov": float(r["overlap"]),
                "elpd": float(r["elpd_loo_per_feature_day"]),
                "e_tau": float(r["e_tau"]),
                "k": float(r["loo_pareto_k_max"]),
            }
        )

    metric = r"$\overline{\mathrm{elpd}}/(F\cdot E')$"
    etau = r"$\mathbb{E}[\tau]$"
    khat = r"max $\hat k$"

    md = [
        "# Top-10 mean-only by normalized elpd (PSIS-LOO)",
        "",
        "Source: `figures/data/mean_only_long.csv` ($n=84$). "
        "Ranking metric = `elpd_loo_per_feature_day` = "
        + metric
        + ".",
        "",
        f"| # | features | lik | $N$ | ov | {metric} | {etau} | {khat} |",
        "|---|---|---|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        md.append(
            f"| {r['rank']} | `{r['features']}` | {r['lik']} | {r['N']} | {r['ov']:g} | "
            f"{r['elpd']:.3f} | {r['e_tau']:.2f} | {r['k']:.2f} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")

    tex_lines = [
        "% Auto-generated by figures/make_loo_topk_table.py — do not edit by hand.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Top-10 mean-only cells by $\overline{\mathrm{elpd}}/(F\cdot E')$ ($n=84$).}",
        r"  \label{tab:loo-topk}",
        r"  \setlength{\tabcolsep}{3.5pt}",
        r"  \renewcommand{\arraystretch}{1.05}",
        r"  \begin{tabular}{@{}r l l r r r r r@{}}",
        r"    \toprule",
        r"    \# & features & lik & $N$ & ov & "
        r"$\overline{\mathrm{elpd}}$ & $\mathbb{E}[\tau]$ & $\hat k_{\max}$ \\",
        r"    \midrule",
    ]
    for r in rows:
        ov = f"{r['ov']:.2f}" if r["ov"] else "0"
        tex_lines.append(
            f"    {r['rank']} & \\texttt{{{feat_tex(r['features'])}}} & {r['lik']} & "
            f"{r['N']} & {ov} & {r['elpd']:.3f} & {r['e_tau']:.2f} & {r['k']:.2f} \\\\"
        )
    tex_lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
    ]
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(tex_lines), encoding="utf-8")
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
