"""REM chunk feature engineering for changepoint models."""

from .rem_chunk_features import (
    build_group_data,
    compute_chunk_feature_map,
    compute_chunk_features,
    compute_concat_chunk_feature_map,
    compute_shape_shift,
    expected_fixed_n_chunk_count,
    expected_fixed_n_chunks,
    group_data_from_precomputed,
    load_and_normalize,
    maxmin_scale,
    precompute_all_features,
    prepare_model_data,
    prepare_variant_data,
    shape_shift_tau_chunk_indices,
    set_runtime_data_norm,
)
from .runtime import (
    ChangepointRunContext,
    get_context,
    get_runtime_data_norm,
    get_runtime_data_raw,
    get_runtime_export_cfg,
    get_runtime_prepare_cfg,
    set_context,
    set_runtime_data_raw,
    set_runtime_export_cfg,
    set_runtime_prepare_cfg,
)

__all__ = [
    "ChangepointRunContext",
    "build_group_data",
    "compute_chunk_feature_map",
    "compute_chunk_features",
    "compute_concat_chunk_feature_map",
    "compute_shape_shift",
    "expected_fixed_n_chunk_count",
    "expected_fixed_n_chunks",
    "get_runtime_data_raw",
    "get_context",
    "get_runtime_data_norm",
    "get_runtime_export_cfg",
    "get_runtime_prepare_cfg",
    "group_data_from_precomputed",
    "load_and_normalize",
    "maxmin_scale",
    "precompute_all_features",
    "prepare_model_data",
    "prepare_variant_data",
    "shape_shift_tau_chunk_indices",
    "set_context",
    "set_runtime_data_norm",
    "set_runtime_data_raw",
    "set_runtime_export_cfg",
    "set_runtime_prepare_cfg",
]
